### ISSUE TITLE
关于新项目的整体优化建议

### ISSUE THREAD

**Issue by DLmaster361** [Shasnow/StarRailAssistant#1]
## 参考项目
实际上，已有类似的成熟软件可以实现模拟器上的日常代理，如：`LmeSzinc/StarRailCopilot`，能够为您的项目提供设计思路上的参考。
- 注意：我并未觉得本项目会被另一个更完美软件上位替代，因为本项目支持客户端，而我上面所提另一个方案仅支持模拟器，这二者都有其不可或缺的意义，我非常高兴能见到这样优质的开源项目
## 用户安全
关于您对用户账号密码的观点，我有一些异议。须知，公开源代码这一行为除了会让更多用户接触到该软件外，还会增加其它安全风险。当软件推广开来，不法分子可能会了解到本项目，并为其木马程序添加几行代码，自动搜索本地疑似账号密码的文件。实际上，当前的木马病毒就已有通过模糊搜索`key`、`password`等关键词匹配账号密码并实施盗号的功能。因此，本地加密才能切实保护密码安全。事实上，本人同样开发了一款类似的软件`AUTO_MAA`，您可以在我的主页看到这个项目。其中使用的本地混合加密算法，也许可以为您解决这一问题。
- 注意：本人的`AUTO_MAA`项目使用GPL开源，这意味着一旦使用其中的代码，您需要使用相同的协议开源您的项目。如您不愿意使用GPL，更倾向于MIT等更宽松的协议，甚至是不愿开源，请在`AUTO_MAA`的 Issues 中提交申请
## GUI优化
页面当前缺乏分区线，建议使用 groupbox 等进行划分。
## 项目本身优化
1. 通过`GitHub action`自动发布 Issues 简化更新流程，同样可以参考`AUTO_MAA`项目的实现方法
2. 增加`requirements.txt`文件储存项目的依赖，方便开发者部署
3. 如这是一个开源项目，请添加`license`。公开源代码不等于开源，只有添加上使用的协议，才算开源。如不开源，请告知

---------------------------

愿此行，终抵群星

另：用方舟的图做软件图标是不是夹带私货也太明显了点？

**Comment by Shasnow** [comment]
@DLmaster361 感谢您为SRA的发展提供的参考和宝贵建议！
## 关于安全性问题
已经关注到您提及的可能有不法分子通过木马病毒扫描本地文件盗取账号的问题，我们会尝试在后续的更新中采用加密算法来保护用户隐私。
## 关于GUI
感谢您的建议。目前项目的主功能代码和图形化代码全都由一人负责，我们还需要一些时间来让GUI变得美观。
## 关于项目
感谢您的建议。如您所见，借助SRA的契机，我首次注册到GitHub并在其中创建了项目分享给他人。我们还需要一些时间来学习如何使用GitHub来让我们的项目变得更好。   
我们确信SRA会是一个开源的项目，并且会在仔细思考后添加`license`。
## 关于软件图标
~小特很可爱~  
感谢你的提问。事实上，我们还未最终确定软件的图标，如果您有更好的意见，欢迎向我们提出！
******  
感谢您对SRA的关注与支持！
*愿此行，终抵群星*
