### ISSUE TITLE
清开拓力-拟造花萼（赤）连续作战次数与设定不一致

### ISSUE THREAD

**Issue by MarkRentang** [Shasnow/StarRailAssistant#12]
今天在使用过程中出现了界面设定连续作战次数6次，脚本实际只设置了3次的异常现象，附上设置界面与log
![Uploading 屏幕截图 2024-10-17 231215.png…]()
[
[log.txt](https://github.com/user-attachments/files/17414944/log.txt)
](url)

**Comment by MarkRentang** [comment]
[log.txt](https://github.com/user-attachments/files/17415055/log.txt)

**Comment by Shasnow** [comment]
@MarkRentang 感谢您的反馈！  
根据您的描述，我们猜测您正在使用v0.6.2以前的版本，如果是这样，请更新到最新的版本，这应该能解决您的问题。  
如果更新后解决了您的问题，且您没有更多问题，此issue将在12小时后关闭。
