### ISSUE TITLE
有关窗口的建议

### ISSUE THREAD

**Issue by xb114514-nmls** [Shasnow/StarRailAssistant#13]
1. 可以添加记住**窗口位置&大小**的功能
2. 可以更改功能选择和任务设置组框大小让他在生成窗口的时候就能显示全部的按钮，或者添加最小宽度确保程序被缩放到最小时可以显示完全
附：125%缩放下程序默认启动时的界面
![startup](https://github.com/user-attachments/assets/5cc69eef-0c9b-40b3-ac22-d5258464848e)

**Comment by Shasnow** [comment]
感谢您的意见，相关功能已经实现，将在下一次更新中包含！
