### ISSUE TITLE
自动更新出问题

### ISSUE THREAD

**Issue by SoSlowA** [Shasnow/StarRailAssistant#16]
如题，更新0.7.1后SRAUpdater似乎无法正常工作，报错：('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))（如下图）
![image](https://github.com/user-attachments/assets/86e97084-91bd-4f92-8fb6-a35278b1c866)
Github能正常访问，打开Watt Toolkits加速也不行。

**Comment by Shasnow** [comment]
@SoSlowA  感谢您的反馈！
我们早已注意到这个问题并在数日前发布了更新来修复它，然而由于旧的更新器使用的代理网站失效、旧更新器无法正常工作，您可能无法接收到更新推送，这需要您手动下载最新的更新器来覆盖旧的更新器，下载链接：[SRA更新器](https://github.com/Shasnow/StarRailAssistant/releases/download/v0.7.0/SRAUpdater.zip)
