### ISSUE TITLE
关于未来功能的建议

### ISSUE THREAD

**Issue by Shotazt** [Shasnow/StarRailAssistant#8]
1.目前清体力的时候是否有切换队伍使用支援角色的功能？
2.是否有除了清体力以外获得日常活跃点的方式，例如合成物品，升级遗器等，防止个别极端情况可能会发生日常活跃点不足无法全领
3.未来是否会自己写或和其他项目合作
扩展新功能，例如锄大地，宇宙，忘却等功能
4.账号切换功能是否类似于这个项目直接切换https://github.com/babalae/mihoyo-starter
6.是否有游戏后台检测并自动切换到前台，如果开着游戏端的时候
5.其他建议想到再继续提交
(≧ω≦)/

**Comment by Shasnow** [comment]
@Shotazt 感谢你的提问。
* 清体力的时候是否有切换队伍使用支援角色的功能？
  * 目前暂无此功能，清体力使用当前出战队伍。
* 其他获取活跃点的方式？
  * 暂无，目前SRA假定在理想情况下通过上线、派遣、清体力即可达到500活跃点，能够满足大部分场景。因极端情况导致无法领满奖励的问题等待后续优化。
* 未来的新功能？
  * 未来将接入由`符玄`开发的`穷观阵`(占卜小玩具)；考虑到实现难度，`模拟宇宙`相关功能或许会在相当长一段时间后才会推出；`忘却之庭`, `虚构叙事`, `末日幻影`对配队、角色练度、操作要求极高，可能不会推出这些功能；对于`锄大地`，考虑到对此功能需求较小，以及市面上已经存在实现了此功能的项目，我们认为SRA中不会再推出此功能。
* 账号切换功能？
  * 目前我们对此功能的实现尚无定论，初步规划为操作游戏退出到登录界面--登出账号--输入要切换的账号--登录。
* 是否有游戏后台检测并自动切换到前台？
  * 是的，您无需担忧，我们早已实现此功能，在你点击按钮开始任务时，如果存在运行中的游戏进程，SRA会将其激活到前台，无论它是处于后台还是最小化。

------
感谢您对SRA的关注与支持！
*愿此行，终抵群星*

**Comment by shotamiao** [comment]
7.抽卡记录的获取保存及其导出链接（2024.10.6)

**Comment by shotamiao** [comment]
8.采用https://mirror.ghproxy.com/
很多脚本作者都喜欢使用的GitHub加速器进行拉取此脚本的链接进行下载解压替换文件~~~~

**Comment by shotamiao** [comment]
9.通过对游戏打开后界面识别到的提示（例如更新完重启游戏，或者更新客户端等）进行识别，采取不同方案执行，例如第一个采取结束游戏进程并再次打开，第二个则选择打开米哈游启动器识别崩铁游戏图标选择后进行游戏大版本更新，不断在屏幕相应位置进行识别下一步的文字，例如启动游戏等可能会出现的操作。

**Comment by shotamiao** [comment]
10.是否有一个可以直接让用户启动脚本的文件，直接运行用户已经设置好的系列举措，用完整运行来代替这个描述，而不启动图形化gui再进行下一步的操作，实战例如用户可能会使用Windows自带的任务管理器定时一键启动脚本

**Comment by shotamiao** [comment]
11.在设置中新增，能关闭系统HDR，修改游戏分辨率等影响脚本进行的功能（开启选项后，会自动修改分辨率至合适脚本的分辨率，又在关闭脚本后自己恢复原有分辨率）

**Comment by shotamiao** [comment]
12.支持国际服英文版崩铁的启动和脚本正常运行，目前崩铁脚本还有海外大量潜在用户（这个功能属于非常困难级别，建议留到非常后面）
